apiVersion: apps/v1
kind: Deployment

spec:
  replicas: 1
  selector:
    
        containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 109
