apiVersion: apps/v1
kind: Deployment

spec:
  replicas: 1
  selector:
    
  template:
      metadata:
        name: v
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 109
